# Generated by Django 6.0.1 on 2026-06-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited per customer. 1 = one-time per user/guest.'),
        ),
    ]
