# Generated by Django 6.0.1 on 2026-06-22 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_coupon_code_order_discount'),
        ('promotions', '0002_coupon_per_user_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('coupon', 'order'), name='uniq_redemption_coupon_order'),
        ),
    ]
