# Generated by Django 6.0.1 on 2026-07-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('kind', models.CharField(choices=[('test_connection', 'Test connection'), ('webhook', 'Webhook'), ('verify', 'Verify capture'), ('refund', 'Refund'), ('finalize', 'Finalize')], max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='Provider event/charge id — idempotency key.', max_length=120)),
                ('order_number', models.CharField(blank=True, default='', max_length=40)),
                ('payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('ok', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('reason_safe', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment event',
                'verbose_name_plural': 'Payment monitor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('is_enabled', models.BooleanField(default=False, help_text='Use this config for checkout. OFF by default.')),
                ('environment', models.CharField(choices=[('test', 'Test / sandbox'), ('live', 'Live')], default='test', max_length=10)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('stripe_publishable_key', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_api_base', models.CharField(blank=True, default='', help_text='Leave blank to derive from the environment.', max_length=120)),
                ('stripe_secret_key_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('stripe_secret_key_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('stripe_secret_key_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('stripe_secret_key_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('stripe_webhook_secret_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('stripe_webhook_secret_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('stripe_webhook_secret_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('stripe_webhook_secret_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('paypal_secret_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('paypal_secret_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('paypal_secret_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('paypal_secret_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('secret_updated_by', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('allow_checkout', models.BooleanField(default=False, help_text='Superuser only. Keep OFF until tested.')),
                ('allow_live_mode', models.BooleanField(default=False, help_text='Superuser only. Required to use live keys.')),
                ('last_connection_check_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_connection_status', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('last_connection_error_safe', models.CharField(blank=True, default='', editable=False, max_length=200)),
                ('last_connection_detail_safe', models.CharField(blank=True, default='', editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment provider',
                'verbose_name_plural': 'Payment providers',
                'ordering': ['provider'],
            },
        ),
    ]
