# Generated by Django 6.0.1 on 2026-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='allow_capture',
            field=models.BooleanField(default=False, help_text='Superuser only. Keep OFF by default.'),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='allow_refund',
            field=models.BooleanField(default=False, help_text='Superuser only. Keep OFF by default.'),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, default='', help_text='PayPal webhook id (not a secret).', max_length=120),
        ),
    ]
