# Generated by Django 6.0.1 on 2026-01-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_product_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_variant_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
