# Generated by Django 6.0.1 on 2026-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_blueprint_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
