# Generated by Django 6.0.1 on 2026-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_cost',
            field=models.FloatField(default=0.0, help_text='Default production cost per unit (Printify). Variant-level cost overrides this when available.'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, default='', help_text='Washing / care guidance'),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.IntegerField(blank=True, help_text="Optional 'was' price for sale display", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default='', help_text="Materials / composition, e.g. '100% organic cotton'"),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_notes',
            field=models.TextField(blank=True, default='', help_text='Fit & sizing notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_provider_id',
            field=models.IntegerField(blank=True, help_text='Printify print provider id (for shipping/cost)', null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='production_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
