# Generated by Django 6.0.1 on 2026-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_base_cost_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_sync_status',
            field=models.CharField(choices=[('not_synced', 'Not synced'), ('synced', 'Synced'), ('updated', 'Updated'), ('draft', 'Draft'), ('error', 'Sync error')], default='not_synced', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
