# Generated by Django 6.0.1 on 2026-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shipping', 'Shipping & delivery'), ('returns', 'Returns & refunds'), ('payments', 'Payments & security'), ('orders', 'Orders & tracking'), ('account', 'Account & wishlist'), ('sizing', 'Sizing & products'), ('coupons', 'Coupons & offers'), ('support', 'Support & assistant')], default='support', max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('question_it', models.CharField(blank=True, default='', max_length=200)),
                ('question_fr', models.CharField(blank=True, default='', max_length=200)),
                ('answer', models.TextField()),
                ('answer_it', models.TextField(blank=True, default='')),
                ('answer_fr', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General FAQ',
                'verbose_name_plural': 'General FAQs',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
