# Generated by Django 6.0.1 on 2026-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_reviewrating_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_blueprint_title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_options_summary',
            field=models.CharField(blank=True, default='', help_text="e.g. 'Sizes: S–XXL · Colours: 5'", max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_provider_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_tags',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_visible',
            field=models.BooleanField(default=True, help_text='Mirrors Printify product visibility'),
        ),
    ]
