# Generated by Django 6.0.1 on 2026-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_printify_blueprint_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_default', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='printify_mockup_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='printify_position',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='productimage',
            name='printify_src',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='productimage',
            name='printify_variant_ids',
            field=models.TextField(blank=True, default='', help_text='Comma-separated Printify variant ids'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_grams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_is_enabled',
            field=models.BooleanField(default=True, help_text='Disabled variants are admin-visible but not buyable'),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_sku',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_supplier_price',
            field=models.FloatField(default=0.0, help_text='Printify retail price hint (admin)'),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
