# Generated by Django 6.0.1 on 2026-06-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescriptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Target language code, e.g. 'it', 'fr'", max_length=5)),
                ('source_hash', models.CharField(help_text='Hash of the English source at translation time', max_length=64)),
                ('translated_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('error', 'Error')], default='done', max_length=12)),
                ('error_code', models.CharField(blank=True, default='', help_text='Safe error code only (never raw provider output/keys)', max_length=40)),
                ('translated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_translations', to='store.product')),
            ],
            options={
                'verbose_name': 'Product description translation',
                'indexes': [models.Index(fields=['product', 'language'], name='store_produ_product_f625a3_idx')],
                'unique_together': {('product', 'language')},
            },
        ),
    ]
