# Generated by Django 6.0.1 on 2026-07-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productdescriptiontranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_description_raw',
            field=models.TextField(blank=True, default='', help_text='Original (uncleaned) Printify description as received at sync time — admin reference only, never rendered to customers'),
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_value', models.CharField(help_text='Lowercased colour Variation.variation_value', max_length=100)),
                ('image_ids', models.TextField(blank=True, default='', help_text='Ordered comma-separated ProductImage ids for this colour')),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic'), ('heuristic', 'Heuristic'), ('openai', 'OpenAI'), ('manual', 'Manual')], default='deterministic', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('detail', models.CharField(blank=True, default='', help_text='Short provenance note (safe — no keys, no raw AI output)', max_length=200)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_image_maps', to='store.product')),
            ],
            options={
                'verbose_name': 'Product colour-image map',
                'indexes': [models.Index(fields=['product', 'color_value'], name='store_produ_product_cb868e_idx')],
                'unique_together': {('product', 'color_value')},
            },
        ),
    ]
