# Generated by Django 6.0.1 on 2026-07-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_printify_description_raw_productcolorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImageMapRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', help_text="Admin username/email or 'cli'", max_length=150)),
                ('mode', models.CharField(choices=[('dry_run', 'Dry run'), ('apply', 'Apply')], default='dry_run', max_length=12)),
                ('source', models.CharField(choices=[('db', 'DB data'), ('live', 'Live payload refetch')], default='db', max_length=12)),
                ('use_openai', models.BooleanField(default=False)),
                ('max_ai_calls', models.IntegerField(default=0)),
                ('only_unresolved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=12)),
                ('products_scanned', models.IntegerField(default=0)),
                ('products_changed', models.IntegerField(default=0)),
                ('colors_resolved', models.IntegerField(default=0)),
                ('colors_unresolved', models.IntegerField(default=0)),
                ('manual_preserved', models.IntegerField(default=0)),
                ('openai_calls_used', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('safe_summary_json', models.JSONField(blank=True, default=dict, help_text='Safe per-product rows (no secrets)')),
                ('safe_error', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Colour-image mapping run',
                'ordering': ['-created_at'],
            },
        ),
    ]
