# Generated by Django 6.0.1 on 2026-08-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productcolorimagemaprun'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printify_express_eligible',
            field=models.BooleanField(default=False, help_text='Printify reports this product as Express-eligible'),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_express_enabled',
            field=models.BooleanField(default=False, help_text='Express is switched on for this product in Printify'),
        ),
        migrations.AddField(
            model_name='variation',
            name='printify_express_eligible',
            field=models.BooleanField(default=False, help_text='Printify reports this variant as Express-eligible'),
        ),
    ]
