# Generated by Django 6.0.1 on 2026-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='printify_variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
