# Generated by Django 6.0.1 on 2026-06-20 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_carrier_order_cost_production_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('requested', 'Return requested'), ('approved', 'Return approved'), ('rejected', 'Return rejected'), ('refunding', 'Refund in progress'), ('refunded', 'Refunded'), ('closed', 'Closed')], default='requested', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('within_window', models.BooleanField(default=True)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
            ],
            options={
                'verbose_name': 'Return request',
                'verbose_name_plural': 'Return requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
        ),
    ]
