# Generated by Django 6.0.1 on 2026-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
