# Generated by Django 6.0.1 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show in customer filters / nav / sitemap. Uncheck for technical categories.'),
        ),
    ]
