# Generated by Django 6.0.1 on 2026-06-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0011_alter_reviewrating_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_it', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle_fr', models.CharField(blank=True, default='', max_length=200)),
                ('hero_title', models.CharField(blank=True, default='', max_length=160)),
                ('hero_title_it', models.CharField(blank=True, default='', max_length=160)),
                ('hero_title_fr', models.CharField(blank=True, default='', max_length=160)),
                ('image', models.URLField(blank=True, default='')),
                ('meta_description', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on the homepage.')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='store.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('title_it', models.CharField(blank=True, default='', max_length=140)),
                ('title_fr', models.CharField(blank=True, default='', max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('description_it', models.CharField(blank=True, default='', max_length=300)),
                ('description_fr', models.CharField(blank=True, default='', max_length=300)),
                ('image', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchored_outfits', to='store.product')),
                ('products', models.ManyToManyField(blank=True, related_name='outfits', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductNotificationSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('variant', models.CharField(blank=True, default='', max_length=80)),
                ('notify_type', models.CharField(choices=[('back_in_stock', 'Back in stock'), ('new_drop', 'New drop')], default='back_in_stock', max_length=20)),
                ('consent', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_signups', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('complete_look', 'Complete the look'), ('alternative', 'Alternative'), ('best_match', 'Best match')], default='related', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='store.product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('from_product', 'to_product', 'relation_type'), name='uniq_product_relation'), models.CheckConstraint(condition=models.Q(('from_product', models.F('to_product')), _negated=True), name='relation_not_self')],
            },
        ),
    ]
