# Generated by Django 6.0.1 on 2026-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='editorial_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='editorial_intro_fr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='editorial_intro_it',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='mood',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('bold', 'Bold'), ('everyday', 'Everyday'), ('street', 'Street'), ('soft', 'Soft'), ('gift_ready', 'Gift-ready')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='season',
            field=models.CharField(blank=True, choices=[('new_season', 'New season'), ('essentials', 'Essentials'), ('gifts', 'Gifts'), ('summer', 'Summer'), ('winter', 'Winter')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='collection',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
