# Generated by Django 6.0.1 on 2026-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandising', '0002_collection_editorial_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.URLField(blank=True, default='', help_text="Hero image URL. If empty, a collage of the collection's real product images is shown automatically."),
        ),
    ]
