# Generated by Django 6.0.1 on 2026-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('products', 'Products sync'), ('costs', 'Variant costs sync'), ('orders', 'Order status pull'), ('single_product', 'Single product resync')], default='products', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Success'), ('partial', 'Partial'), ('error', 'Error')], default='running', max_length=10)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Printify sync log',
                'verbose_name_plural': 'Printify sync logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
