# Generated by Django 6.0.1 on 2026-06-22 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0001_initial'),
        ('store', '0013_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifyShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_id', models.IntegerField(db_index=True)),
                ('blueprint_title', models.CharField(blank=True, default='', max_length=160)),
                ('print_provider_id', models.IntegerField(db_index=True)),
                ('print_provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('country_code', models.CharField(db_index=True, max_length=4)),
                ('first_item_cost', models.FloatField(default=0.0)),
                ('additional_item_cost', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('handling_days', models.IntegerField(default=3)),
                ('min_delivery_days', models.IntegerField(default=0)),
                ('max_delivery_days', models.IntegerField(default=0)),
                ('source', models.CharField(default='printify', max_length=16)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Printify shipping profile',
                'verbose_name_plural': 'Printify shipping profiles',
                'ordering': ['blueprint_id', 'country_code'],
                'constraints': [models.UniqueConstraint(fields=('blueprint_id', 'print_provider_id', 'country_code'), name='uniq_printify_shipping_profile')],
            },
        ),
        migrations.CreateModel(
            name='PrintifyPrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_id', models.IntegerField(blank=True, null=True)),
                ('print_provider_id', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=40)),
                ('placeholder_count', models.IntegerField(default=0)),
                ('has_print_file', models.BooleanField(default=False)),
                ('variant_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_areas', to='store.product')),
            ],
            options={
                'verbose_name': 'Printify print area',
                'verbose_name_plural': 'Printify print areas',
                'ordering': ['product', 'position'],
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='uniq_printify_print_area')],
            },
        ),
    ]
