# Generated by Django 6.0.1 on 2026-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0002_printifyshippingprofile_printifyprintarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifyShippingEstimateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_hash', models.CharField(db_index=True, max_length=64)),
                ('country_code', models.CharField(db_index=True, max_length=4)),
                ('postal_prefix', models.CharField(blank=True, default='', max_length=8)),
                ('shipping_method', models.CharField(default='standard', max_length=24)),
                ('source', models.CharField(default='local_fallback', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('shipping_cost', models.FloatField(default=0.0)),
                ('production_days_min', models.IntegerField(default=0)),
                ('production_days_max', models.IntegerField(default=0)),
                ('transit_days_min', models.IntegerField(default=0)),
                ('transit_days_max', models.IntegerField(default=0)),
                ('delivery_days_min', models.IntegerField(default=0)),
                ('delivery_days_max', models.IntegerField(default=0)),
                ('raw_response_safe', models.JSONField(blank=True, default=dict, help_text='Per-method cost map (cents). No PII, no token.')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Printify shipping estimate (cached)',
                'verbose_name_plural': 'Printify shipping estimates (cached)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cart_hash', 'country_code', 'postal_prefix', 'shipping_method'], name='idx_ship_estimate_lookup')],
            },
        ),
    ]
