# Generated by Django 6.0.1 on 2026-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0003_printifyshippingestimatecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=120)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('backoff_until', models.DateTimeField(blank=True, null=True)),
                ('backoff_level', models.IntegerField(default=0)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_status', models.IntegerField(blank=True, null=True)),
                ('products_synced_total', models.BigIntegerField(default=0)),
                ('last_tick_synced', models.IntegerField(default=0)),
                ('last_tick_requests', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printify sync state',
                'verbose_name_plural': 'Printify sync state',
            },
        ),
    ]
