# Generated by Django 6.0.1 on 2026-07-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0004_printifysyncstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintifyAccountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary', max_length=80)),
                ('is_active', models.BooleanField(default=False, help_text='Use this account for sync / test connection.')),
                ('shop_id', models.CharField(blank=True, default='', max_length=40)),
                ('token_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('token_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('token_last_four', models.CharField(blank=True, default='', editable=False, max_length=4)),
                ('token_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('token_updated_by', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('last_connection_check_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_connection_status', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('last_connection_error_safe', models.CharField(blank=True, default='', editable=False, max_length=200)),
                ('last_connection_shop_name', models.CharField(blank=True, default='', editable=False, max_length=120)),
                ('last_connection_product_count', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('sync_interval_seconds', models.PositiveIntegerField(default=1800)),
                ('sync_mode', models.CharField(choices=[('dry_run', 'Dry run — read only, no DB writes'), ('read_only', 'Read-only catalog — cache reads, no writes'), ('apply_catalog', 'Apply catalog (safe) — update local catalog only')], default='dry_run', max_length=20)),
                ('allow_product_publish', models.BooleanField(default=False, help_text='Superuser only. Keep OFF.')),
                ('allow_order_creation', models.BooleanField(default=False, help_text='Superuser only. Keep OFF.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Printify account',
                'verbose_name_plural': 'Printify accounts',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
