# Generated by Django 6.0.1 on 2026-07-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0005_printifyaccountconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='printifyaccountconfig',
            name='shop_sales_channel',
            field=models.CharField(blank=True, default='', editable=False, max_length=60),
        ),
        migrations.AddField(
            model_name='printifyaccountconfig',
            name='shop_selected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='printifyaccountconfig',
            name='shop_title',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
    ]
