# Generated by Django 6.0.1 on 2026-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printify_integration', '0006_printifyaccountconfig_shop_sales_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printifysyncstate',
            options={'verbose_name': 'Printify Sync Monitor', 'verbose_name_plural': 'Printify Sync Monitor'},
        ),
        migrations.AddField(
            model_name='synclog',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='synclog',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='synclog',
            name='hidden_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='missing_image_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='missing_price_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synclog',
            name='shop_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='synclog',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
