# Generated by Django 6.0.1 on 2026-06-21 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier, e.g. 'returns-window'.", max_length=80, unique=True)),
                ('category', models.CharField(choices=[('shipping', 'Shipping'), ('returns', 'Returns'), ('refunds', 'Refunds'), ('payments', 'Payments'), ('sizing', 'Sizing'), ('account', 'Account'), ('tracking', 'Tracking'), ('product', 'Product'), ('ondemand', 'Print on demand'), ('support', 'Support'), ('privacy', 'Privacy'), ('general', 'General')], default='general', max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('question_it', models.CharField(blank=True, default='', max_length=255)),
                ('question_fr', models.CharField(blank=True, default='', max_length=255)),
                ('answer', models.TextField()),
                ('answer_it', models.TextField(blank=True, default='')),
                ('answer_fr', models.TextField(blank=True, default='')),
                ('keywords', models.TextField(blank=True, default='', help_text='Comma-separated retrieval keywords (all languages).')),
                ('priority', models.IntegerField(default=0, help_text='Higher shows first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge entry',
                'verbose_name_plural': 'Knowledge base',
                'ordering': ['-priority', 'category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('language', models.CharField(blank=True, default='en', max_length=5)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='Salted hash — never the raw IP.', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant conversation',
                'verbose_name_plural': 'Assistant conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=12)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, default='', help_text='openai | fallback | mock | guardrail', max_length=20)),
                ('grounded', models.BooleanField(default=True, help_text='False when the assistant declined for lack of context.')),
                ('used_sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.assistantmessage')),
            ],
            options={
                'verbose_name': 'Assistant feedback',
                'verbose_name_plural': 'Assistant feedback',
            },
        ),
    ]
