# Generated by Django 6.0.1 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch: the assistant calls OpenAI only when ON. OFF = curated-knowledge fallback mode (still useful).')),
                ('model', models.CharField(default='gpt-4o-mini', help_text='OpenAI model id used for answers.', max_length=64)),
                ('temperature', models.FloatField(default=0.4)),
                ('max_input_chars', models.PositiveIntegerField(default=600)),
                ('max_output_tokens', models.PositiveIntegerField(default=350)),
                ('rate_limit_per_session', models.PositiveIntegerField(default=12, help_text='Messages allowed per session per 10 minutes.')),
                ('system_prompt_extra', models.TextField(blank=True, default='', help_text='Optional store-specific guidance appended to the built-in safe prompt. Never overrides the safety rules.')),
                ('api_key_ciphertext', models.TextField(blank=True, default='')),
                ('api_key_fingerprint', models.CharField(blank=True, default='', max_length=16)),
                ('api_key_last_four', models.CharField(blank=True, default='', max_length=8)),
                ('api_key_set_at', models.DateTimeField(blank=True, null=True)),
                ('last_connection_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_connection_detail', models.CharField(blank=True, default='', max_length=200)),
                ('last_connection_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant AI settings',
                'verbose_name_plural': 'Assistant AI settings',
            },
        ),
    ]
