# Generated by Django 6.0.1 on 2026-07-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. OFF = plain manual address entry.')),
                ('enable_autocomplete', models.BooleanField(default=False, help_text='Load Google Places Autocomplete on the checkout address field.')),
                ('enable_address_validation', models.BooleanField(default=False, help_text='Server-side Google Address Validation (warning-only, never blocks).')),
                ('maps_browser_key', models.CharField(blank=True, default='', help_text='Places JS browser key — public by design; restrict it by referrer in the Google console. Never use a server key here.', max_length=100)),
                ('allowed_domains_note', models.CharField(blank=True, default='', help_text='Reminder of the referrer restrictions configured in the Google console.', max_length=200)),
                ('server_key_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('server_key_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('server_key_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('server_key_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('secret_updated_by', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('last_connection_status', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('last_connection_check_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_connection_detail_safe', models.CharField(blank=True, default='', editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkout API settings',
                'verbose_name_plural': 'Checkout API settings',
            },
        ),
    ]
