# Generated by Django 6.0.1 on 2026-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutapiconfig',
            name='validation_mode',
            field=models.CharField(choices=[('disabled', 'Disabled — manual entry, local checks only'), ('warning', 'Warning — unverified addresses need an explicit confirmation'), ('strict', 'Strict — only Google-verified addresses can order')], default='disabled', help_text='How hard to enforce address verification at checkout. Strict needs Google configured; it degrades to Warning if neither key is usable.', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutapiconfig',
            name='enable_address_validation',
            field=models.BooleanField(default=False, help_text='Server-side Google Address Validation (used by the mode below).'),
        ),
    ]
