# Generated by Django 6.0.1 on 2026-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_printify_last_error_order_printify_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
