# Generated by Django 6.0.1 on 2026-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_manual_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
