# Generated by Django 6.0.1 on 2026-07-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_address_manual_confirmed_and_more'),
        ('store', '0015_product_printify_description_raw_productcolorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='selected_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.productimage'),
        ),
    ]
