# Generated by Django 6.0.1 on 2026-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderproduct_selected_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, default='standard', max_length=24),
        ),
    ]
