# Generated by Django 6.0.1 on 2026-06-20 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_carrier_order_cost_production_and_more'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('consent', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='website', max_length=64)),
                ('welcomed', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order.created', 'order.created'), ('order.paid', 'order.paid'), ('order.in_production', 'order.in_production'), ('order.shipped', 'order.shipped'), ('order.tracking_available', 'order.tracking_available'), ('return.requested', 'return.requested'), ('return.approved', 'return.approved'), ('return.rejected', 'return.rejected'), ('refund.completed', 'refund.completed'), ('cart.abandoned', 'cart.abandoned'), ('printify.error', 'printify.error'), ('margin.negative', 'margin.negative'), ('newsletter.subscribed', 'newsletter.subscribed'), ('support.autoreply', 'support.autoreply'), ('internal.alert', 'internal.alert')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('skipped', 'Skipped (n8n disabled)')], default='pending', max_length=16)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('language', models.CharField(default='en', max_length=5)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orders.order')),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='returns.returnrequest')),
            ],
            options={
                'verbose_name': 'Outbound event',
                'verbose_name_plural': 'Outbound events (Django → n8n)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'event_type'], name='notificatio_status_ac869d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('attachments_meta', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=16)),
                ('is_auto_replied', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='orders.order')),
            ],
            options={
                'verbose_name': 'Support message',
                'verbose_name_plural': 'Support messages (inbound)',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('message_id',), name='uniq_non_empty_message_id')],
            },
        ),
    ]
