# Generated by Django 6.0.1 on 2026-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundevent',
            name='event_type',
            field=models.CharField(choices=[('order.created', 'order.created'), ('order.paid', 'order.paid'), ('order.in_production', 'order.in_production'), ('order.shipped', 'order.shipped'), ('order.tracking_available', 'order.tracking_available'), ('return.requested', 'return.requested'), ('return.approved', 'return.approved'), ('return.rejected', 'return.rejected'), ('refund.completed', 'refund.completed'), ('cart.abandoned', 'cart.abandoned'), ('printify.error', 'printify.error'), ('margin.negative', 'margin.negative'), ('newsletter.subscribed', 'newsletter.subscribed'), ('support.autoreply', 'support.autoreply'), ('support.order_help', 'support.order_help'), ('internal.alert', 'internal.alert')], max_length=64),
        ),
    ]
