# Generated by Django 6.0.1 on 2026-06-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_outboundevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundevent',
            name='event_type',
            field=models.CharField(choices=[('order.created', 'order.created'), ('order.paid', 'order.paid'), ('order.in_production', 'order.in_production'), ('order.shipped', 'order.shipped'), ('order.tracking_available', 'order.tracking_available'), ('return.requested', 'return.requested'), ('return.approved', 'return.approved'), ('return.rejected', 'return.rejected'), ('refund.completed', 'refund.completed'), ('cart.abandoned', 'cart.abandoned'), ('printify.error', 'printify.error'), ('margin.negative', 'margin.negative'), ('newsletter.subscribed', 'newsletter.subscribed'), ('support.autoreply', 'support.autoreply'), ('support.order_help', 'support.order_help'), ('style_quiz_completed', 'style_quiz_completed'), ('product_notification_signup', 'product_notification_signup'), ('outfit_add_to_cart', 'outfit_add_to_cart'), ('wishlist_reminder', 'wishlist_reminder'), ('cart_saved_for_later', 'cart_saved_for_later'), ('high_intent_user', 'high_intent_user'), ('internal.alert', 'internal.alert')], max_length=64),
        ),
    ]
