# Generated by Django 6.0.1 on 2026-08-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_outboundevent_event_type'),
        ('orders', '0011_order_shipping_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('order', 'Order question'), ('payment', 'Payment problem'), ('delivery', 'Delivery and tracking'), ('returns', 'Return or refund'), ('product', 'Product information'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('order_number', models.CharField(blank=True, default='', max_length=40)),
                ('message', models.TextField(max_length=4000)),
                ('language', models.CharField(blank=True, default='en', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('closed', 'Closed')], db_index=True, default='pending', max_length=12)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='contact_page', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='notifications.outboundevent')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Contact request',
                'verbose_name_plural': 'Contact requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='notificatio_status_304319_idx')],
            },
        ),
    ]
