# Generated by Django 6.0.1 on 2026-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Use this configuration. OFF = fall back to server env/settings.')),
                ('provider', models.CharField(choices=[('smtp', 'SMTP (send email directly)'), ('n8n', 'n8n (delegate sending to the automation)'), ('console', 'Console (write emails to the log — testing)'), ('disabled', 'Disabled (do not send email)')], default='smtp', max_length=12)),
                ('support_email', models.EmailField(blank=True, default='', help_text='Customer-facing support address (contact page, assistant, legal).', max_length=254)),
                ('admin_notify_email', models.EmailField(blank=True, default='', help_text='Where contact-form and internal alerts are delivered.', max_length=254)),
                ('default_from_email', models.CharField(blank=True, default='', help_text='From: on outbound mail. Name <addr@…> is allowed.', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, default='', help_text='Optional Reply-To on outbound mail.', max_length=254)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=254)),
                ('smtp_password_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('smtp_password_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('smtp_password_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('smtp_password_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('n8n_mail_enabled', models.BooleanField(default=False, help_text='Route mail through an n8n webhook configured here (else the server env is used).')),
                ('n8n_webhook_url', models.URLField(blank=True, default='', help_text='n8n mail webhook base URL. Not a secret, but keep it internal.')),
                ('n8n_secret_ciphertext', models.TextField(blank=True, default='', editable=False)),
                ('n8n_secret_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=16)),
                ('n8n_secret_last_four', models.CharField(blank=True, default='', editable=False, max_length=8)),
                ('n8n_secret_set_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('secret_updated_by', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('last_test_status', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('last_test_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_test_error_safe', models.CharField(blank=True, default='', editable=False, max_length=250)),
                ('last_test_detail_safe', models.CharField(blank=True, default='', editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', editable=False, max_length=150)),
            ],
            options={
                'verbose_name': 'Email configuration',
                'verbose_name_plural': 'Email configuration',
            },
        ),
    ]
