# Generated by Django 6.0.1 on 2026-06-21 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Analytics event',
                'verbose_name_plural': 'Analytics events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160)),
                ('message_it', models.CharField(blank=True, default='', max_length=160)),
                ('message_fr', models.CharField(blank=True, default='', max_length=160)),
                ('link_url', models.CharField(blank=True, default='', help_text='Optional CTA link (relative or absolute).', max_length=255)),
                ('link_label', models.CharField(blank=True, default='', max_length=40)),
                ('link_label_it', models.CharField(blank=True, default='', max_length=40)),
                ('link_label_fr', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('dismissible', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when several are active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
