# Generated by Django 6.0.1 on 2026-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(db_index=True, help_text='Which homepage image this replaces.', max_length=40, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Internal label — never shown to customers.', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_visuals/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Optional portrait crop for phones.', null=True, upload_to='site_visuals/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Describes the image for screen readers and SEO. Required when uploading.', max_length=200)),
                ('focal_point_x', models.PositiveSmallIntegerField(default=50, help_text='Horizontal focus %, 0 = left, 100 = right.')),
                ('focal_point_y', models.PositiveSmallIntegerField(default=50, help_text='Vertical focus %, 0 = top, 100 = bottom.')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to instantly restore the original image.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Site visual',
                'verbose_name_plural': 'Site visuals',
                'ordering': ['slot'],
            },
        ),
    ]
